### ISSUE TITLE
colorsys not a pip package

### ISSUE THREAD

**Issue by PicoJr** [tsarjak/Simulate-Correct-ColorBlindness#2]
Hello,

It looks like the `colorsys` is not a pip package but is part of the standard lib instead (python2/3)

* <https://docs.python.org/2.7/library/colorsys.html>
* <https://docs.python.org/3.5/library/colorsys.html>

Maybe the line from the README: `sudo pip install Pillow colorsys numpy`

should be replaced with `sudo pip install Pillow numpy` ?

Take care, awesome project btw =)

**Comment by tsarjak** [comment]
Oh alright! I'll make the change!

Thank you for pointing and also for the appreciation! Cheers!
