### ISSUE TITLE
picture rotated when applying a transformation ?

### ISSUE THREAD

**Issue by PicoJr** [tsarjak/Simulate-Correct-ColorBlindness#3]
Hello,

It appears that pictures are rotated during the transformation:

![picojr](https://user-images.githubusercontent.com/31004690/45865342-7ff31980-bd7d-11e8-833e-e8eb908f5069.png)

![picojr-st](https://user-images.githubusercontent.com/31004690/45865254-2db1f880-bd7d-11e8-8168-458017b9380a.png)

I haven't found out what is the cause for it yet ^^

But since it occurs for each transformation:

> I guess it involves a function that is called regardless of the transformation.

Take care,

**Comment by PicoJr** [comment]
After further investigation:

Conversion to LMS seems to be the cause for the 1/4 rotation

* image arrays are matrices -> line i, column j, rgb k -> top right pixel is (0, width)
* PIllow images -> cartesian with origin top left -> top right pixel is (width, 0)

edit: the suggestion below only works for **square ratio** pictures.

`editablePhoto[i,j,k] = photo[i,j][k]` should be `editablePhoto[i,j,k] = photo[j,i][k]`

As for the symmetry, the normalization seems to be the cause.

I must admit I don't understand why a normalization is required ^^

Did you find the algorithm described somewhere?

Take care,

**Comment by tsarjak** [comment]
> After further investigation:
> 
> Conversion to LMS seems to be the cause for the 1/4 rotation
> 
> * image arrays are matrices -> line i, column j, rgb k -> top right pixel is (0, width)
> * PIllow images -> cartesian with origin top left -> top right pixel is (width, 0)
> 
> edit: the suggestion below only works for **square ratio** pictures.
> 
> `editablePhoto[i,j,k] = photo[i,j][k]` should be `editablePhoto[i,j,k] = photo[j,i][k]`
> 
> As for the symmetry, the normalization seems to be the cause.
> 
> I must admit I don't understand why a normalization is required ^^
> 
> Did you find the algorithm described somewhere?
> 
> Take care,

Yes, I have the link to the paper. Also checkout the updated version. It fixes all the issues.
https://arxiv.org/pdf/1711.10662.pdf
